fix: optimize sticky scroll bar visible check
react-component/table pull request #1078
Opened 2024-02-07 07:46 UTC by linxianxi

2024-02-07 07:49 UTC, zombieJ commented on src/stickyScrollBar.tsx
> +  const bodyHeight = scrollBodyRef.current.offsetHeight;
`scrollBodyRef.current?.offsetHeight` ?

2024-02-07 08:00 UTC, linxianxi commented on src/stickyScrollBar.tsx
> +  const bodyHeight = scrollBodyRef.current.offsetHeight;
漏了，我补一下，居然没提示

2024-02-07 12:28 UTC, afc163 commented on src/stickyScrollBar.tsx
> +  const bodyHeight = scrollBodyRef.current?.offsetHeight;
render 阶段内不应该读 dom，服务端渲染会挂。

2024-02-07 12:28 UTC, afc163 requested changes
render 阶段内不应该读 dom，服务端渲染会挂。

2024-02-20 07:54 UTC, linxianxi commented on src/stickyScrollBar.tsx
> +  const bodyHeight = scrollBodyRef.current?.offsetHeight;
加了可选链也不行？

2024-02-20 08:52 UTC, afc163 commented on src/stickyScrollBar.tsx
> +  const bodyHeight = scrollBodyRef.current?.offsetHeight;
就不应该去操作 dom。

2024-03-29 04:55 UTC, closed without merging